on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: ts-to-zod
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.releases_created }}
      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Build Packages
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          pnpm install
          pnpm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
